---
services:
  consolemodz:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: consolemodz
    network_mode: bridge
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SUBFOLDER=/
      - TITLE=consolemodz
    volumes:
      - $(pwd)/config:/config
      - $(pwd)/custom-cont-init.d:/custom-cont-init.d
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped
